r"""
Small linear algebra utilities for free modules over an algebra.

These routines are intended to work with Sage's
``CombinatorialFreeModule`` class and related structures.
"""
from sage.combinat.free_module import CombinatorialFreeModule
from sage.matrix.constructor import Matrix


def algebra_to_free_module_elt(omega, CFM):
    r"""
    Return the image of an algebra element in a free module.

    This is an internal function for sage_periods, and is not 
    meant to be called by the user.

    INPUT:

    * ``omega`` -- An element of a finite-dimensional $A$-algebra $M$.
    * ``CFM`` -- A Sage ``CombinatorialFreeModule`` over $A$ whose
      basis elements correspond to elements of $M$.

    ASSUMPTIONS:

    * $M$ is a free, finitely generated $A$-module.
    * ``omega`` lies in $M$.
    * ``CFM`` is generated by monomials of the ring $M$.

    OUTPUT:

    * ``out`` -- The representation of ``omega`` in ``CFM``.

    EXAMPLES:

    A nontrivial example.

            sage: var('t x0 x1 x2')
            sage: K = PolynomialRing(QQ,t)
            sage: t = K.gen()
            sage: A = PolynomialRing(K,[x0,x1,x2])
            sage: x = A.gens()
            sage: CFM = CombinatorialFreeModule(K,[x[0]**2, x[2]*x[1], x[2]*x[1]*x[0]**3])
            sage: omega = 3/t*(x[0]**2) + (2-t)*x[2]*x[1] + 7*(x[2]*4*x[1]*x[0]**3)
            sage: algebra_to_free_module_elt(omega,CFM)
            (-t+2)*B[x1*x2] + 3/t*B[x0^2] + 28*B[x0^3*x1*x2]

    A trivial example.

            sage: CFM_triv = CombinatorialFreeModule(K,[A(x[0])])
            sage: omega_triv = A(7*t - 3) + A(3*x[0])
            sage: algebra_to_free_module_elt(omega_triv,CFM_triv)
            (7*t-3)*B[1] + 3*B[x0]

    !!! warning
        If we pass in a component that is not part of our basis, a portion
        for it is created in the output. But this is ignored when converting
        back using ``free_module_to_algebra_elt``.
            
    """
    assert all( g.is_monomial() for g in CFM.get_order()), "CFM should be generated by monomial basis!"
    # Need to check if we have the zero vector for v, else next line will fail
    if omega == omega.parent(0):
        return CFM.zero()

    # Extract lists of monomials and coefficients of the algebra element
    mons = omega.monomials()
    coeffs = omega.coefficients()

    return (CFM.zero()
            + sum([coeffs[i] * CFM.monomial(mons[i])
                   for i in range(len(mons))]))


def free_module_to_algebra_elt(v, CFM):
    r"""
    Convert a free-module element back to the algebra.

    This is an internal function for sage_periods, and is not 
    meant to be called by the user.

    INPUT:

    * ``v`` -- An element of the free module ``CFM``.
    * ``CFM`` -- A Sage ``CombinatorialFreeModule``.

    OUTPUT:

    * An element of the corresponding algebra ``M``.

    EXAMPLES:

    A Nontrivial example.

            sage: var('t x0 x1 x2')
            sage: K = PolynomialRing(QQ,t)
            sage: t = K.gen()
            sage: A = PolynomialRing(K,[x0,x1,x2])
            sage: x = A.gens()
            sage: CFM = CombinatorialFreeModule(K,[x[0]**2, x[2]*x[1], x[2]*x[1]*x[0]**3])
            sage: v = CFM.random_element()
            sage: v
            (12*t^2+2/35*t+1/2)*B[x1*x2] + 5*t*B[x0^3*x1*x2]
            sage: free_module_to_algebra_elt(v,CFM)
            5*t*x0^3*x1*x2 + (12*t^2 + 2/35*t + 1/2)*x1*x2
            
    A trivial example.

            sage: CFM_triv = CombinatorialFreeModule(K,[A(x[0])])
            sage: omega_triv = A(7*t - 3) + 3*t*x[0]
            sage: v = algebra_to_free_module_elt(omega_triv,CFM_triv)
            sage: v
            (7*t-3)*B[1] + 3*t*B[x0]
            sage: free_module_to_algebra_elt(v,CFM_triv)
            3*t*x0

    !!! warning
        If v has a component that is NOT part of our basis for CFM then this is truncated.

    """
    basis = CFM.get_order()
    if (v == CFM.zero()):
        return basis[0].parent(0)
    return sum([v[b] * b for b in basis])


def mons_in_ring_order(L):
    r"""
    Return monomials appearing in a list of polynomials.

    This is an internal function for sage_periods, and is not 
    meant to be called by the user.

    INPUT:    
    * ``L`` -- A list of elements of some multivariate polynomial ring ``A``.

    ASSUMPTIONS:

    * All elements in L belong to the same polynomial ring ``A``

    OUTPUT:

    * List of monomials of ``A`` appearing in the polynomials of ``L``,
      ordered according to the monomial order on ``A`` (greatest to least).

    EXAMPLES:

    A nontrivial example.

            sage: var('t x0 x1 x2')
            sage: K = PolynomialRing(QQ,t)
            sage: t = K.gen()
            sage: A = PolynomialRing(K,[x0,x1,x2])
            sage: x = A.gens()
            sage: f_arr = [ A.random_element() for i in range(5)]
            sage: f_arr
            [(t^2 + 1/2*t)*x1^2 + (-3*t^2 + t)*x0*x2 + (t^2 + 17/7*t)*x2^2 + (-3/2*t^2)*x2 + t^2 - 3*t + 1/3, (t^2 + 1/4*t + 13)*x0*x1 - x0*x2 + (1/7*t^2 - 7*t - 1/2)*x1*x2 + (9/4*t^2 - 1)*x2^2, (8*t + 1)*x0*x1 + (t^2 + 1)*x2^2 + (-t^2 + 7*t - 1/2)*x1 + (t^2 + t - 1/6)*x2 - 43/7*t^2 - 1/29*t + 2, (-23/48*t^2 - 3*t - 3/7)*x0*x1 + (2*t^2 - 1/4*t - 2/3)*x1^2 + (6*t^2 - t + 1)*x2^2 + (1/4*t^2 - t - 1/7)*x1 - 4/3*t^2 - 10*t - 1/10, (-43*t - 1)*x1^2 + 2*t*x2^2 + (-87)*x0 + (-t^2 + 1)*x2 + 1/4*t - 1]
            sage: mons_in_ring_order(f_arr)
            [x0*x1, x1^2, x0*x2, x1*x2, x2^2, x0, x1, x2, 1]
            
    A trivial example.

            sage: mons_in_ring_order([])
            []
            sage: mons_in_ring_order([A(0)])
            []
      
    """
    if not L:
        return []

    mons = set()
    for p in L:
        if (p.parent() != A):
            # This should never be printed.
            print("mons_in_ring_order: Had to cast element of input list to polynomial ring.")
            p = A(p)
        for m in p.monomials():
            mons.add(m)
    dummy_poly = A(0)
    for m in mons:
        dummy_poly += m               # Coefficient 1 means no cancellation
    return dummy_poly.monomials()     # Now in A’s monomial order


def echelonized_basis_poly(L, return_matrix=False):
    r"""
    Return a (reduced) echelonized basis for the span of a list of polynomials.
    That is, return a basis $B$ for span$_{\mathbb{K}}(L)$ such that for each $b \in B$ the leading monomial 
    of $b$ doesn't appear with nonzero coefficient in any other leading monomials of elements of $B$.

    This is an internal function for sage_periods, and is not 
    meant to be called by the user.

    INPUT:

    * ``L`` -- A list of elements of a multivariate polynomial ring ``A`` over a field ``K``.
    * ``return_matrix`` -- (Optional) A boolean with default value ``False``. 

    ASSUMPTIONS:

    * All elements in ``L`` have the same parent ``A``, a polynomial ring.

    OUTPUT:

    * A list of polynomials forming a basis for the $\mathbb{K}$-span of $L$ in
      echelon form. If ``return_matrix`` is ``True`` then a pair
      ``(basis, M)`` is returned, where ``M`` is the echelonized matrix
      whose rows correspond to the basis elements.

    NOTES:

    * ``L`` should consist of a list of vectors representing elements
        in a finite-dimensional ``A``-module.
    * The polynomial ring ``A`` should have grevlex order, which is
        compatible with the TOP order on our ``A``-module extending ``grevlex``.

    EXAMPLES:

    A nontrivial example.

            sage: var('t x0 x1 x2')
            sage: p = 7
            sage: A = PolynomialRing(GF(p),[x0,x1,x2])
            sage: x = A.gens()
            sage: f_arr = [ A.random_element() for i in range(5)]
            sage: f_arr
            [3*x0^2 + 2*x2^2 + 3*x0 - 2, -2*x0*x1 - 3*x1^2 - 3*x0*x2 - x2^2 - 3*x2, x0^2 - 3*x0*x1 - 3*x2^2 - x0, 3*x1^2 - 3*x0*x2 - 3*x2^2 + x0 - x1, -x0^2 - x0*x1 - x1*x2 + 3*x2^2 + x0]
            sage: echelonized_basis_poly(f_arr,False)
            [x0^2 + 3*x2^2 + x0 - 3, x0*x1 + 2*x2^2 + 3*x0 - 1, x1^2 - x2^2 - 2*x0 + x1 - 3*x2 - 2, x0*x2 - x1 - 3*x2 - 2, x1*x2 - x2^2 + 2*x0 - 3]
                                                                                                                                                                                                                                        0                                                                                                                                                                                                                                   0                                                                                                                                                                                                                                   0                                                                                                                                                                                                                                   0                                                                                                                                                                                                                                   1                                                                                                                                                                                            (-3/224*t^2 - 57/14)/(t^2 + 3/7*t + 3/7)                                                                                                                                                                                                           3/7*t/(t^2 + 3/7*t + 3/7)                                                                                                                                                                                                   (3/7*t + 6/7)/(t^2 + 3/7*t + 3/7)                                                                                                                                                                                                 (-9/14*t + 3/7)/(t^2 + 3/7*t + 3/7)                                                                                                                                                                                                                                   0]

    A trivial example.

            sage: echelonized_basis_poly([],False)
            []
            sage: echelonized_basis_poly([A(0)],False)
            []

    !!! note

            This method also works over $Q$, $Q(t)$, etc.
        
    """
    # Corner case / get A:
    if not L:
        return []
    A = L[0].parent()

    # Enumerate all monomials appearing in ``L`` and order
    # them with respect to the monomial order on ``A``.
    mons = mons_in_ring_order(L)

    # Build the K-vector space of all such monomials with this order,
    # and convert all elements of ``L`` to vectors in this space.
    V = CombinatorialFreeModule(A.base_ring(), mons)
    L_vecs = [algebra_to_free_module_elt(l, V) for l in L]

    # Get coordinates
    L_coords = [[v.coefficient(m) for m in V.get_order()] for v in L_vecs]

    # Form a matrix from these vectors and take RREF; this
    # gives an echelonized basis in coordinates.
    mat = Matrix(A.base_ring(), L_coords).rref()

    # Convert rows back to polynomials and return only the nonzero rows.
    rows = [row for row in mat.rows() if row.is_zero() is False]
    if return_matrix:
        return Matrix(rows)
    else:
        return [
            free_module_to_algebra_elt(
                V.from_vector(row), V
            )
            for row in rows
        ]
    

def linear_normal_form_p(L0 , M, reduce):
    r"""
    Reduce multivariate polynomials modulo an already-echelonized list, directly in polynomial form.
    
    We assume $M$ is already echelonized, so reduction is performed simply by cancelling each leading 
    monomial of $M$ in all entries of $L_0$.

    This is an internal function for sage_periods, and is not 
    meant to be called by the user.
    
    INPUT:
    
    * ``L0`` -- A sequence of multivariate polynomials to reduce.
    * ``M`` -- An echelonized sequence of multivariate polynomials.
    * ``reduce`` -- A boolean flag signalling whether to echelonize the output again.
    
    OUTPUT:
    
    * A sequence of polynomial normal forms modulo the span of M.

    EXAMPLES:

    A nontrivial example.

            sage: var('t x0 x1 x2')
            sage: p = 7
            sage: A = PolynomialRing(GF(p),[x0,x1,x2])
            sage: x = A.gens()
            sage: B = echelonized_basis_poly([ A.random_element() for i in range(3)],A,False)
            sage: linear_normal_form_p([A.random_element() for i in range(2)],B,reduce=False)
            [-x0^2 - x1 + x2 - 3, -2*x0^2 + 2*x2^2 - 2*x0 + 2*x2 + 3]

    You can reduce the result with respect to ``M0`` if you want to.

            sage: linear_normal_form_p([A.random_element() for i in range(2)],B,reduce=True)
            [x0*x1 - x1 + 3*x2 - 2, x2^2 - 3*x2 - 3]

    Trivial examples.

            sage: linear_normal_form_p([],B,False) # Trivial input list
            []
            sage: linear_normal_form_p([A(3*x[2]+1)],[],False) # Trivial basis reduction gives itself.
            [3*x2 + 1]

    """
    L = L0
    # Successively cancel the pivont monomial of each row of M in all targets
    for j in range(len(M)):
        m = M[j].lm()
        for i in range(len(L)):
            c = L[i].monomial_coefficient(m)
            L[i] -= c*M[j]

    if reduce:
        # Optinally normalize the residual family itself
        L = echelonized_basis_poly(L,L[0].parent(),False)
    
    return L